GET http://127.0.0.1:8000/api/posts HTTP/1.1

###

POST http://127.0.0.1:8000/api/posts HTTP/1.1
Content-Type: application/json



{
    "title": "My third title.",
    
    "content": "My third content"
}

###

PUT http://127.0.0.1:8000/api/posts/3 HTTP/1.1
Content-Type: application/json

{
    "title": "My third title (updated)",
    "content": "My thir content (updated)"
}